---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-ossf-scorecard-project-
  namespace: dracon
spec:
  pipelineRef:
    name: dracon-ossf-scorecard-project
  params:
  - name: producer-ossf-scorecard-input-repo
    value: github.com/ossf-tests/scorecard-check-branch-protection-e2e
  - name: producer-ossf-scorecard-github-auth-token
    value: "$GITHUB_TOKEN"
  workspaces:
  - name: source-code-ws
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
