---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -typescript-project

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  - ../../../components/producers/aggregator
  - ../../../components/producers/typescript-npm-audit
  - ../../../components/producers/typescript-eslint
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/elasticsearch
