---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -semgrep-project
namespace: dracon

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  - ../../../components/producers/aggregator
  - ../../../components/producers/semgrep
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/consumers/mongodb
