---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-defectdojo-project-
  namespace: dracon
spec:
  pipelineRef:
    name: dracon-defectdojo-project
  params:
  - name: repository_url
    value:  https://github.com/trufflesecurity/test_keys
  - name: consumer-defectdojo-url
    value: http://defectdojo.cyberdyne.dracon.cloud.localhost:8080/api/v2/
  - name: consumer-defectdojo-user
    value: "admin"
  - name: consumer-defectdojo-token
    value: "the defect dojo api token"
  - name: consumer-defectdojo-product-id
    value: "the numerical id for a defect dojo product under which these vulns will be created"
  workspaces:
  - name: source-code-ws
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
