---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -npm-audit-purl-project
namespace: dracon

resources:
  - ../../../components/base

components:
  - ../../../components/sources/dependency
  - ../../../components/producers/aggregator
  - ../../../components/producers/typescript-npm-audit
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
