---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sign-results-project

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  - ../../../components/producers/aggregator
  - ../../../components/producers/golang-gosec
  - ../../../components/producers/golang-nancy
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/elasticsearch
