---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -ossf-scorecard-project

resources:
  - ../../../components/base

components:
  - ../../../components/producers/aggregator
  - ../../../components/producers/ossf-scorecard
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/elasticsearch
