---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -kics-project

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  - ../../../components/producers/aggregator
  - ../../../components/producers/kics
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/consumers/mongodb
