---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-python-project-
  namespace: dracon
spec:
  pipelineRef:
    name: dracon-python-project
  params:
  - name: repository_url
    value: https://github.com/anxolerd/dvpwa
  workspaces:
  - name: source-code-ws
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
