---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -terraform-project

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  - ../../../components/producers/aggregator
  - ../../../components/producers/terraform-tfsec
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/consumers/mongodb
